<?php
declare(strict_types=1);

// CatherineSchulmanQuotes SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

CatherineSchulmanQuotesUtility::setRegistrar(function (CatherineSchulmanQuotesUtility $u): void {
    $u->clean = [CatherineSchulmanQuotesClean::class, 'call'];
    $u->done = [CatherineSchulmanQuotesDone::class, 'call'];
    $u->make_error = [CatherineSchulmanQuotesMakeError::class, 'call'];
    $u->feature_add = [CatherineSchulmanQuotesFeatureAdd::class, 'call'];
    $u->feature_hook = [CatherineSchulmanQuotesFeatureHook::class, 'call'];
    $u->feature_init = [CatherineSchulmanQuotesFeatureInit::class, 'call'];
    $u->fetcher = [CatherineSchulmanQuotesFetcher::class, 'call'];
    $u->make_fetch_def = [CatherineSchulmanQuotesMakeFetchDef::class, 'call'];
    $u->make_context = [CatherineSchulmanQuotesMakeContext::class, 'call'];
    $u->make_options = [CatherineSchulmanQuotesMakeOptions::class, 'call'];
    $u->make_request = [CatherineSchulmanQuotesMakeRequest::class, 'call'];
    $u->make_response = [CatherineSchulmanQuotesMakeResponse::class, 'call'];
    $u->make_result = [CatherineSchulmanQuotesMakeResult::class, 'call'];
    $u->make_point = [CatherineSchulmanQuotesMakePoint::class, 'call'];
    $u->make_spec = [CatherineSchulmanQuotesMakeSpec::class, 'call'];
    $u->make_url = [CatherineSchulmanQuotesMakeUrl::class, 'call'];
    $u->param = [CatherineSchulmanQuotesParam::class, 'call'];
    $u->prepare_auth = [CatherineSchulmanQuotesPrepareAuth::class, 'call'];
    $u->prepare_body = [CatherineSchulmanQuotesPrepareBody::class, 'call'];
    $u->prepare_headers = [CatherineSchulmanQuotesPrepareHeaders::class, 'call'];
    $u->prepare_method = [CatherineSchulmanQuotesPrepareMethod::class, 'call'];
    $u->prepare_params = [CatherineSchulmanQuotesPrepareParams::class, 'call'];
    $u->prepare_path = [CatherineSchulmanQuotesPreparePath::class, 'call'];
    $u->prepare_query = [CatherineSchulmanQuotesPrepareQuery::class, 'call'];
    $u->graphql_body = [CatherineSchulmanQuotesGraphql::class, 'body'];
    $u->graphql_errors = [CatherineSchulmanQuotesGraphql::class, 'errors'];
    $u->result_basic = [CatherineSchulmanQuotesResultBasic::class, 'call'];
    $u->result_body = [CatherineSchulmanQuotesResultBody::class, 'call'];
    $u->result_headers = [CatherineSchulmanQuotesResultHeaders::class, 'call'];
    $u->transform_request = [CatherineSchulmanQuotesTransformRequest::class, 'call'];
    $u->transform_response = [CatherineSchulmanQuotesTransformResponse::class, 'call'];
});
